[package]
org = "ballerinax"
name = "wso2.icp"
version = "0.1.0"
distribution = "2201.13.1"
repository = "https://github.com/ballerina-platform/module-ballerinax-wso2.icp"
license = ["Apache-2.0"]

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
path = "../native/build/libs/wso2.icp-native-0.1.0-SNAPSHOT.jar"
