[package]
org = "ballerinax"
name = "wso2.icp"
version = "1.0.4"
distribution = "2201.13.2-20260212-143500-e5b29948"
repository = "https://github.com/ballerina-platform/module-ballerinax-wso2.icp"
license = ["Apache-2.0"]

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
path = "../native/build/libs/wso2.icp-native-1.0.4-SNAPSHOT.jar"
